language: node_js
node_js:
  - "10"

before_install:
  - cd lib

env:
  - CMD='test:date-fns'
  - CMD='test:luxon'
  - CMD='test:moment'
  - CMD='build:analyze'
  - CMD='lint'

script: npm run $CMD

jobs:
  include:
    - stage: e2e
      script:
        - cd ..
        - npm ci
        - lerna run build
        - lerna run serve & npx wait-on http://localhost:3002 && npm run e2e:run -- --record
